import type { LanguagePack, LanguagePackId } from "@/lib/languagePackTypes";

export const PACKS: Record<LanguagePackId, LanguagePack> = {
  default: {
    appTitle: "Adoption Framework Renderer",
    appSubtitle: "Paste a JSON document that conforms to language.schema.json.",
    inputJson: "Input JSON",
    renderedView: "Rendered view",
    readablePreviewClassic: "Classic",
    readablePreviewBrowse: "Browse layout",
    readablePreviewFullDocument: "Full document",
    loadExample: "Load example",
    validateAndRender: "Validate & Render",
    downloadPdf: "Download PDF",
    editAsForm: "Edit as form",
    editAsJson: "Edit as JSON",
    applyJsonToDocument: "Apply JSON",
    saveToLibrary: "Save to library",
    discardLibraryChanges: "Discard changes",
    discardLibraryConfirm: "Discard all unsaved edits and reload the copy from the library?",
    editingLibraryDocument: "Library document — save or discard to sync storage.",
    savingLabel: "Saving…",
    discardFailed: "Could not reload from library.",
    saveFailedPrefix: "Could not save",
    documentTypeLockedHint: "Document type is fixed for this saved library practice.",
    practiceAuthorStandaloneLead:
      "Save to library adds the current practice as a new library entry. Open an item from the library to edit a saved document in place.",
    saveMissingDocumentId: "Save succeeded but no document id was returned.",
    browseTableOfContents: "Table of contents",
    libraryDelete: "Delete",
    libraryDeleteConfirm: 'Remove "{name}" from the library? This cannot be undone.',
    libraryDeleteFailed: "Could not delete the document.",
    libraryDeleting: "Deleting…",
    libraryDeleteAllPractices: "Delete all practices",
    libraryDeleteAllPracticesTitle:
      "Permanently remove every extension practice in the library (documents with baselinePracticeName). Methods and baseline practices are not deleted. Ignores sidebar folder and tag filters.",
    libraryDeleteAllPracticesConfirm:
      "You are about to permanently delete {count} extension practice document(s) from the library.\n\nMethods and baseline practices will NOT be affected.\n\nThis cannot be undone. Do you want to continue?",
    libraryDeleteAllPracticesConfirmFinal:
      "Final confirmation: delete all {count} extension practice document(s) now? Click OK to remove them.",
    libraryDeletingAllPractices: "Deleting practices…",
    libraryDeleteAllPracticesNone: "There are no extension practice documents in the library to delete.",
    libraryDeleteAllPracticesPartial:
      "Removed some practices but {failed} of {total} could not be deleted. Check the message below or try again.",
    browseTocOverview: "Overview",
    browseTocDependencies: "Dependencies",
    browseWorkProductsUnderAlphas: "Work products",
    nothingToRender: "Nothing to render yet. Click Validate & Render.",
    schemaIssuesTitle: "Schema validation issues",
    refIssuesTitle: "Cross-reference issues",

    viewText: "Text",
    viewDiagramFocusAlphas: "Diagram: Focuses & Alphas",
    viewDiagramActivitySpaces: "Diagram: Activity Spaces & Activities",

    pdfDiagramFocusAlphas: "Diagram: Focuses & Alphas",
    pdfDiagramActivitySpaces: "Diagram: Activity Spaces & Activities",
    pdfTextRender: "Text render",

    sectionAlphas: "Alphas",
    sectionActivities: "Activities",
    implicitFocusName: "Dependencies",
    alphasAndStates: "Alphas & States",
    activitySpaces: "Activity Spaces",
    competencies: "Competencies",
    contributesTo: "Contributes to",
    alphaContributesToAlpha: "Contributes to alpha",
    alphaSupportingAlphas: "Supporting alphas",
    alphaStatesSection: "States",
    requiredCompetencies: "Required competencies",
    levels: "Levels",

    alpha: "Alpha",
    state: "State",
    activitySpace: "Activity Space",
    competency: "Competency",

    practiceActivity: "Activity",
    withinActivitySpace: "Within activity space",
    withinRollupAlpha: "Roll-up alpha",
    worksOn: "Works on",
    recommendedCompetencyLevels: "Recommended competency levels",
    tags: "Tags",
    tagsDomain: "Domain tags",
    tagsLifecycle: "Lifecycle tags",
    tagsOrganizational: "Organizational tags",
    checklist: "Checklist",
    checklistSeq: "Sequence",
    checklistVerificationMethod: "Verification method",
    checklistEvidencedBy: "Evidenced by",
    activityParentSpace: "Parent activity space",
    levelOfDetailSeq: "Level sequence",
    narrativeTypesHeading: "Narrative spine types",
    elementNarrativesHeading: "Element narratives",
    narrativeElementsHeading: "Spine elements",
    narrativeContextsHeading: "Narrative contexts",
    narrativeContextSeq: "Context sequence",
    personasHeading: "Personas",
    personaGroupsHeading: "Persona groups",
    personaGroupMembers: "Personas in group",
    activitySpaceInvolvesPersonaGroups: "Persona groups involved",
    patternNarrativeTypeName: "Narrative type",
    patternViewNarrativeElementName: "Narrative element",
    patternViewsHeading: "Pattern views",
    patternMatrixExpandAllLanes: "Expand all lanes",
    patternMatrixCollapseAllLanes: "Collapse all lanes",
    patternMatrixShowLanesCount: "Show lanes ({count})",
    patternMatrixHideSliceLanes: "Hide lanes",
    patternViewAlphaStates: "Alpha → state slices",
    patternViewActivitySpaces: "Activity space lanes",
    patternViewActivities: "Activity lanes",
    practiceElementAliasesHeading: "Name aliases",
    keywords: "Keywords",
    libraryTagFiltersHeading: "Filter by tags",
    libraryClearTagFilters: "Clear tag filters",
    libraryRowActionsMenu: "Actions",
    libraryDownloadAllJson: "Download library as JSON",
    libraryDownloadingAllJson: "Exporting…",
    methodBrowseExtensionPracticesHeading: "Extension practices composing this method",
    extendsBaseline: "Extends baseline practice",
    practiceDependencies: "Other practices",
    workProducts: "Work products",

    patterns: "Patterns",
    patternViewLanes: "Activity spaces & activities",
  },
  alt: {
    appTitle: "Renderer",
    appSubtitle: "Paste a valid framework document.",
    inputJson: "Source JSON",
    renderedView: "Document",
    readablePreviewClassic: "Classic",
    readablePreviewBrowse: "Browse layout",
    readablePreviewFullDocument: "Full document",
    loadExample: "Load sample",
    validateAndRender: "Render",
    downloadPdf: "Download PDF",
    editAsForm: "Edit as form",
    editAsJson: "Edit as JSON",
    applyJsonToDocument: "Apply JSON",
    saveToLibrary: "Save to library",
    discardLibraryChanges: "Discard changes",
    discardLibraryConfirm: "Drop local edits and reload the saved library copy?",
    editingLibraryDocument: "Library document — save or discard to update storage.",
    savingLabel: "Saving…",
    discardFailed: "Could not reload from library.",
    saveFailedPrefix: "Could not save",
    documentTypeLockedHint: "Document type cannot be changed for this saved practice.",
    practiceAuthorStandaloneLead:
      "Save to library saves the current practice as a new entry. From the library, open an item to edit saved JSON in place.",
    saveMissingDocumentId: "Save succeeded without a document id.",
    browseTableOfContents: "Contents",
    libraryDelete: "Remove",
    libraryDeleteConfirm: 'Remove "{name}" from the library? This cannot be undone.',
    libraryDeleteFailed: "Could not delete the document.",
    libraryDeleting: "Deleting…",
    libraryDeleteAllPractices: "Delete all practices",
    libraryDeleteAllPracticesTitle:
      "Remove every extension practice in the library (documents that name a baseline). Methods and baseline practices stay. Ignores sidebar filters.",
    libraryDeleteAllPracticesConfirm:
      "You are about to permanently delete {count} extension practice document(s).\n\nMethods and baseline practices are not removed.\n\nThis cannot be undone. Continue?",
    libraryDeleteAllPracticesConfirmFinal:
      "Final check: delete all {count} extension practice document(s) now? OK removes them.",
    libraryDeletingAllPractices: "Deleting practices…",
    libraryDeleteAllPracticesNone: "No extension practice documents are in the library.",
    libraryDeleteAllPracticesPartial:
      "Some deletes failed ({failed} of {total}). See the error detail or retry.",
    browseTocOverview: "Overview",
    browseTocDependencies: "Dependencies",
    browseWorkProductsUnderAlphas: "Deliverables",
    nothingToRender: "Nothing rendered yet.",
    schemaIssuesTitle: "Schema issues",
    refIssuesTitle: "Reference issues",

    viewText: "Text",
    viewDiagramFocusAlphas: "Diagram: Lanes & Concepts",
    viewDiagramActivitySpaces: "Diagram: Work Areas & Work Items",

    pdfDiagramFocusAlphas: "Diagram: Lanes & Concepts",
    pdfDiagramActivitySpaces: "Diagram: Work Areas & Work Items",
    pdfTextRender: "Text",

    sectionAlphas: "Key concepts",
    sectionActivities: "Work areas",
    implicitFocusName: "Dependencies",
    alphasAndStates: "Key Concepts & Stages",
    activitySpaces: "Work Areas",
    competencies: "Capabilities",
    contributesTo: "Advances",
    alphaContributesToAlpha: "Rolls up to",
    alphaSupportingAlphas: "Composed of",
    alphaStatesSection: "Stages",
    requiredCompetencies: "Requires",
    levels: "Proficiency levels",

    alpha: "Concept",
    state: "Stage",
    activitySpace: "Work Area",
    competency: "Capability",

    practiceActivity: "Work item",
    withinActivitySpace: "Under work area",
    withinRollupAlpha: "Parent concept",
    worksOn: "Produces / uses",
    recommendedCompetencyLevels: "Suggested proficiency",
    tags: "Tags",
    tagsDomain: "Domain tags",
    tagsLifecycle: "Lifecycle tags",
    tagsOrganizational: "Org tags",
    checklist: "Checklist",
    checklistSeq: "Sequence",
    checklistVerificationMethod: "Verification method",
    checklistEvidencedBy: "Evidenced by",
    activityParentSpace: "Parent work area",
    levelOfDetailSeq: "Detail sequence",
    narrativeTypesHeading: "Narrative spine types",
    elementNarrativesHeading: "Element narratives",
    narrativeElementsHeading: "Spine elements",
    narrativeContextsHeading: "Narrative contexts",
    narrativeContextSeq: "Context sequence",
    personasHeading: "Personas",
    personaGroupsHeading: "Persona groups",
    personaGroupMembers: "Personas in group",
    activitySpaceInvolvesPersonaGroups: "Persona groups involved",
    patternNarrativeTypeName: "Narrative type",
    patternViewNarrativeElementName: "Narrative element",
    patternViewsHeading: "Pattern views",
    patternMatrixExpandAllLanes: "Expand all lanes",
    patternMatrixCollapseAllLanes: "Collapse all lanes",
    patternMatrixShowLanesCount: "Show lanes ({count})",
    patternMatrixHideSliceLanes: "Hide lanes",
    patternViewAlphaStates: "Concept → stage slices",
    patternViewActivitySpaces: "Work area lanes",
    patternViewActivities: "Work item lanes",
    practiceElementAliasesHeading: "Aliases",
    keywords: "Keywords",
    libraryTagFiltersHeading: "Filter by tags",
    libraryClearTagFilters: "Clear tag filters",
    libraryRowActionsMenu: "Actions",
    libraryDownloadAllJson: "Download library as JSON",
    libraryDownloadingAllJson: "Exporting…",
    methodBrowseExtensionPracticesHeading: "Practices composing this method",
    extendsBaseline: "Extends foundation",
    practiceDependencies: "Related practices",
    workProducts: "Deliverables",

    patterns: "Patterns",
    patternViewLanes: "Work areas & work items",
  },
};

