import type { LanguagePack, LanguagePackId } from "@/lib/languagePackTypes";

export const PACKS: Record<LanguagePackId, LanguagePack> = {
  default: {
    appTitle: "Adoption Framework Renderer",
    appSubtitle: "Paste a JSON document that conforms to language.schema.json.",
    inputJson: "Input JSON",
    renderedView: "Rendered view",
    readablePreviewClassic: "Classic",
    readablePreviewBrowse: "Browse layout",
    readablePreviewFullDocument: "Full document",
    readablePreviewBusiness: "Business view",
    readablePreviewDelivery: "Delivery view",
    readablePreviewSow: "SOW view",
    deliveryViewEmpty:
      "No activity spaces or activities to show. Define activity spaces with nested activities, practice-level activities, or both.",
    deliveryViewNoActivitiesInSpace: "No activities listed under this activity space.",
    deliveryViewPracticeLevelActivities: "Practice-level activities",
    loadExample: "Load example",
    validateAndRender: "Validate & Render",
    downloadPdf: "Download PDF",
    editAsForm: "Edit as form",
    editAsJson: "Edit as JSON",
    applyJsonToDocument: "Apply JSON",
    saveToLibrary: "Save to library",
    discardLibraryChanges: "Discard changes",
    discardLibraryConfirm: "Discard all unsaved edits and reload the copy from the library?",
    editingLibraryDocument: "Library document — save or discard to sync storage.",
    savingLabel: "Saving…",
    discardFailed: "Could not reload from library.",
    saveFailedPrefix: "Could not save",
    documentTypeLockedHint: "Document type is fixed for this saved library practice.",
    practiceAuthorStandaloneLead:
      "Save to library adds the current practice as a new library entry. Open an item from the library to edit a saved document in place.",
    saveMissingDocumentId: "Save succeeded but no document id was returned.",
    browseTableOfContents: "Table of contents",
    libraryDelete: "Delete",
    libraryDeleteConfirm: 'Remove "{name}" from the library? This cannot be undone.',
    libraryDeleteFailed: "Could not delete the document.",
    libraryDeleting: "Deleting…",
    browseTocOverview: "Overview",
    nothingToRender: "Nothing to render yet. Click Validate & Render.",
    schemaIssuesTitle: "Schema validation issues",
    refIssuesTitle: "Cross-reference issues",

    viewText: "Text",
    viewDiagramFocusAlphas: "Diagram: Focuses & Alphas",
    viewDiagramActivitySpaces: "Diagram: Activity Spaces & Activities",

    pdfDiagramFocusAlphas: "Diagram: Focuses & Alphas",
    pdfDiagramActivitySpaces: "Diagram: Activity Spaces & Activities",
    pdfTextRender: "Text render",

    sectionAlphas: "Alphas",
    sectionActivities: "Activities",
    implicitFocusName: "Dependencies",
    alphasAndStates: "Alphas & States",
    activitySpaces: "Activity Spaces",
    competencies: "Competencies",
    contributesTo: "Contributes to",
    alphaContributesToAlpha: "Contributes to alpha",
    alphaSupportingAlphas: "Supporting alphas",
    alphaStatesSection: "States",
    requiredCompetencies: "Required competencies",
    levels: "Levels",

    alpha: "Alpha",
    state: "State",
    activitySpace: "Activity Space",
    competency: "Competency",

    practiceActivity: "Activity",
    withinActivitySpace: "Within activity space",
    withinRollupAlpha: "Roll-up alpha",
    worksOn: "Works on",
    recommendedCompetencyLevels: "Recommended competency levels",
    tags: "Tags",
    tagsDomain: "Domain tags",
    tagsLifecycle: "Lifecycle tags",
    tagsOrganizational: "Organizational tags",
    checklist: "Checklist",
    checklistSeq: "Sequence",
    checklistBlocking: "Blocking gate",
    checklistThresholdWeight: "Threshold weight",
    checklistVerificationMethod: "Verification method",
    checklistEvidenceRequired: "Evidence required",
    checklistEvidencedBy: "Evidenced by",
    activityParentSpace: "Parent activity space",
    levelOfDetailSeq: "Level sequence",
    wbEstimationUnit: "Estimation unit",
    patternViewsHeading: "Pattern views",
    patternMatrixExpandAllLanes: "Expand all lanes",
    patternMatrixCollapseAllLanes: "Collapse all lanes",
    patternMatrixShowLanesCount: "Show lanes ({count})",
    patternMatrixHideSliceLanes: "Hide lanes",
    patternViewAlphaStates: "Alpha → state slices",
    patternViewActivitySpaces: "Activity space lanes",
    patternViewActivities: "Activity lanes",
    practiceElementAliasesHeading: "Name aliases",
    keywords: "Keywords",
    libraryTagFiltersHeading: "Filter by tags",
    libraryClearTagFilters: "Clear tag filters",
    libraryRowActionsMenu: "Actions",
    libraryDownloadAllJson: "Download library as JSON",
    libraryDownloadingAllJson: "Exporting…",
    methodBrowseExtensionPracticesHeading: "Extension practices composing this method",
    extendsBaseline: "Extends baseline practice",
    practiceDependencies: "Other practices",
    workProducts: "Work products",

    workBreakdowns: "Work breakdowns",
    patterns: "Patterns",
    patternViewLanes: "Activity spaces & activities",
    wbTasks: "Tasks",
    wbPrerequisites: "Prerequisites (pattern views)",
    wbComplexity: "Complexity",
    wbEstimate: "Estimate (low / med / high)",
    implementsActivity: "Implements activity",
    appliesInSpaces: "Applies in activity spaces",
    contractType: "Contract type",
    complexityLevel: "Complexity level",
    productRisks: "Product risks",
    projectRisks: "Project risks",
    complexityValueRisk: "Value risk",
    complexityTechnicalRisk: "Technical risk",
    complexityStakeholderEngagement: "Stakeholder engagement",
  },
  alt: {
    appTitle: "Renderer",
    appSubtitle: "Paste a valid framework document.",
    inputJson: "Source JSON",
    renderedView: "Document",
    readablePreviewClassic: "Classic",
    readablePreviewBrowse: "Browse layout",
    readablePreviewFullDocument: "Full document",
    readablePreviewBusiness: "Business view",
    readablePreviewDelivery: "Delivery view",
    readablePreviewSow: "SOW view",
    deliveryViewEmpty:
      "Nothing to show yet — add activity spaces and activities or practice-level activity rows.",
    deliveryViewNoActivitiesInSpace: "No activities under this space.",
    deliveryViewPracticeLevelActivities: "Practice-level activities",
    loadExample: "Load sample",
    validateAndRender: "Render",
    downloadPdf: "Download PDF",
    editAsForm: "Edit as form",
    editAsJson: "Edit as JSON",
    applyJsonToDocument: "Apply JSON",
    saveToLibrary: "Save to library",
    discardLibraryChanges: "Discard changes",
    discardLibraryConfirm: "Drop local edits and reload the saved library copy?",
    editingLibraryDocument: "Library document — save or discard to update storage.",
    savingLabel: "Saving…",
    discardFailed: "Could not reload from library.",
    saveFailedPrefix: "Could not save",
    documentTypeLockedHint: "Document type cannot be changed for this saved practice.",
    practiceAuthorStandaloneLead:
      "Save to library saves the current practice as a new entry. From the library, open an item to edit saved JSON in place.",
    saveMissingDocumentId: "Save succeeded without a document id.",
    browseTableOfContents: "Contents",
    libraryDelete: "Remove",
    libraryDeleteConfirm: 'Remove "{name}" from the library? This cannot be undone.',
    libraryDeleteFailed: "Could not delete the document.",
    libraryDeleting: "Deleting…",
    browseTocOverview: "Overview",
    nothingToRender: "Nothing rendered yet.",
    schemaIssuesTitle: "Schema issues",
    refIssuesTitle: "Reference issues",

    viewText: "Text",
    viewDiagramFocusAlphas: "Diagram: Lanes & Concepts",
    viewDiagramActivitySpaces: "Diagram: Work Areas & Work Items",

    pdfDiagramFocusAlphas: "Diagram: Lanes & Concepts",
    pdfDiagramActivitySpaces: "Diagram: Work Areas & Work Items",
    pdfTextRender: "Text",

    sectionAlphas: "Key concepts",
    sectionActivities: "Work areas",
    implicitFocusName: "Dependencies",
    alphasAndStates: "Key Concepts & Stages",
    activitySpaces: "Work Areas",
    competencies: "Capabilities",
    contributesTo: "Advances",
    alphaContributesToAlpha: "Rolls up to",
    alphaSupportingAlphas: "Composed of",
    alphaStatesSection: "Stages",
    requiredCompetencies: "Requires",
    levels: "Proficiency levels",

    alpha: "Concept",
    state: "Stage",
    activitySpace: "Work Area",
    competency: "Capability",

    practiceActivity: "Work item",
    withinActivitySpace: "Under work area",
    withinRollupAlpha: "Parent concept",
    worksOn: "Produces / uses",
    recommendedCompetencyLevels: "Suggested proficiency",
    tags: "Tags",
    tagsDomain: "Domain tags",
    tagsLifecycle: "Lifecycle tags",
    tagsOrganizational: "Org tags",
    checklist: "Checklist",
    checklistSeq: "Sequence",
    checklistBlocking: "Blocking gate",
    checklistThresholdWeight: "Threshold weight",
    checklistVerificationMethod: "Verification method",
    checklistEvidenceRequired: "Evidence required",
    checklistEvidencedBy: "Evidenced by",
    activityParentSpace: "Parent work area",
    levelOfDetailSeq: "Detail sequence",
    wbEstimationUnit: "Estimation unit",
    patternViewsHeading: "Pattern views",
    patternMatrixExpandAllLanes: "Expand all lanes",
    patternMatrixCollapseAllLanes: "Collapse all lanes",
    patternMatrixShowLanesCount: "Show lanes ({count})",
    patternMatrixHideSliceLanes: "Hide lanes",
    patternViewAlphaStates: "Concept → stage slices",
    patternViewActivitySpaces: "Work area lanes",
    patternViewActivities: "Work item lanes",
    practiceElementAliasesHeading: "Aliases",
    keywords: "Keywords",
    libraryTagFiltersHeading: "Filter by tags",
    libraryClearTagFilters: "Clear tag filters",
    libraryRowActionsMenu: "Actions",
    libraryDownloadAllJson: "Download library as JSON",
    libraryDownloadingAllJson: "Exporting…",
    methodBrowseExtensionPracticesHeading: "Practices composing this method",
    extendsBaseline: "Extends foundation",
    practiceDependencies: "Related practices",
    workProducts: "Deliverables",

    workBreakdowns: "Work breakdowns",
    patterns: "Patterns",
    patternViewLanes: "Work areas & work items",
    wbTasks: "Tasks",
    wbPrerequisites: "Prerequisites (pattern views)",
    wbComplexity: "Complexity",
    wbEstimate: "Estimate (low / med / high)",
    implementsActivity: "Implements activity",
    appliesInSpaces: "Applies in activity spaces",
    contractType: "Contract type",
    complexityLevel: "Complexity level",
    productRisks: "Product risks",
    projectRisks: "Project risks",
    complexityValueRisk: "Value risk",
    complexityTechnicalRisk: "Technical risk",
    complexityStakeholderEngagement: "Stakeholder engagement",
  },
};

